# Generated by Django 3.1.7 on 2021-02-27 16:02

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название города')),
                ('slug', models.SlugField(unique=True)),
                ('address', models.TextField(blank=True, help_text='Вместе с названием города', null=True, verbose_name='Адрес магазина в городе')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('whatsapp', models.CharField(blank=True, help_text='В формате: 7 707 *** ****', max_length=20, null=True, verbose_name='Whatsapp')),
                ('site_title_by_city', models.CharField(help_text='Например: "Цветы с досатвкой в Караганде"', max_length=110, verbose_name='Заголовок для страницы города')),
                ('site_description_by_city', models.TextField(verbose_name='Описание - description (SEO)')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название повода')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.CharField(default='mdi-', help_text='https://materialdesignicons.com/', max_length=100, verbose_name='Иконка')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Порядковый номер')),
                ('slug', models.SlugField(unique=True)),
                ('public', models.BooleanField(default=True, verbose_name='Опубликовать')),
            ],
            options={
                'verbose_name': 'Повод',
                'verbose_name_plural': 'Поводы',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Миниатюра')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Рекомендация',
                'verbose_name_plural': 'Рекомендации',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название продавца')),
                ('phone', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес магазина')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Продавец',
                'verbose_name_plural': 'Продавцы',
            },
        ),
        migrations.CreateModel(
            name='Sort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название сорта')),
                ('description', models.TextField(verbose_name='Описание')),
                ('miniature', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Миниатюра')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Порядковый номер')),
                ('slug', models.SlugField(unique=True)),
                ('public', models.BooleanField(default=True, verbose_name='Опубликовать')),
            ],
            options={
                'verbose_name': 'Сорт',
                'verbose_name_plural': 'Сорта',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Название товара')),
                ('price', models.IntegerField(verbose_name='Цена товара')),
                ('old_price', models.IntegerField(blank=True, null=True, verbose_name='Старая цена товара(необязательно)')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Основное изображение товара')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Рейтинг товара')),
                ('short_description', models.TextField(verbose_name='Краткое описание товара')),
                ('delivery', models.TextField(blank=True, null=True, verbose_name='Условия доставки')),
                ('composition', models.TextField(blank=True, null=True, verbose_name='Состав')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('future', models.BooleanField(default=False, verbose_name='Рекомендуем')),
                ('flower', models.BooleanField(default=False, verbose_name='Цветы')),
                ('bouquet', models.BooleanField(default=False, verbose_name='Букеты')),
                ('present', models.BooleanField(default=False, verbose_name='Подарок')),
                ('in_the_box', models.BooleanField(default=False, verbose_name='В коробке')),
                ('set', models.BooleanField(default=False, verbose_name='Набор')),
                ('show_on_home_page', models.BooleanField(default=False, verbose_name='На главной')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Порядковый номер')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('public', models.BooleanField(default=True, verbose_name='Опубликовать')),
                ('views', models.PositiveSmallIntegerField(default=0, verbose_name='Количество просмотров')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Опубликован')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('cities', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.city', verbose_name='Наличие в городах')),
                ('reasons', models.ManyToManyField(blank=True, related_name='products', to='shop.Reason', verbose_name='Повод')),
                ('recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.recommendation', verbose_name='Рекомендация')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.seller', verbose_name='Продавец')),
                ('sort', models.ManyToManyField(blank=True, related_name='products', to='shop.Sort', verbose_name='Сорт')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('order', 'price'),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Дополнительные изображения товара')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товара',
            },
        ),
        migrations.CreateModel(
            name='DeliveryBranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название района')),
                ('price', models.PositiveSmallIntegerField(help_text='Необходимо добавить район с нулевой стоиомстью доставки', verbose_name='Цена доставки')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Порядковый номер')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='shop.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Район доставки',
                'verbose_name_plural': 'Районы доставки',
                'ordering': ('order',),
            },
        ),
    ]
