# Generated by Django 3.1.7 on 2021-02-27 17:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210227_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='miniature',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Миниатюра'),
        ),
    ]
