# Generated by Django 3.1.7 on 2021-02-28 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_miniature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='address',
        ),
        migrations.RemoveField(
            model_name='city',
            name='site_description_by_city',
        ),
        migrations.RemoveField(
            model_name='city',
            name='site_title_by_city',
        ),
    ]
