# Generated by Django 3.1.7 on 2021-03-01 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210301_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reason',
            name='description',
        ),
        migrations.RemoveField(
            model_name='reason',
            name='public',
        ),
    ]
