# Generated by Django 3.1.7 on 2021-02-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='Валюта')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Курс (1 ед. валюты в тенге)')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('icon', models.CharField(default='mdi-', help_text='https://materialdesignicons.com/', max_length=155, verbose_name='Иконка курса')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы валют',
                'ordering': ('order',),
            },
        ),
    ]
