# Generated by Django 3.1.7 on 2021-02-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='icon',
        ),
        migrations.AddField(
            model_name='course',
            name='abbr',
            field=models.CharField(default='тг', max_length=5, verbose_name='Аббревиатура'),
        ),
    ]
